title: Yajun Jia
logo: "/images/logo.png?small=true"
description: >
  4+ years of Data Analyst and Research Analyst experience. 
  Possess Master's degree in Research, Measurement & Statistics from Texas A&M University in 2016.
  <br><br>
  Currently pursuing my doctoral degree at Texas A&M University. 
  I'm working as Data/Research Analyst in 3 research centers at Texas A&M University.
  <br><br>
  <a href="https://www.linkedin.com/in/yajun-mia-jia">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
